#include <fstream>
#include <iomanip>
#include <sstream>
#include <string>

#include "unified_planning.pb.h" // Generated by protoc

#include "analysis/relaxed_planning_graph.hpp"
#include "config/cli_parser.hpp"
#include "config/config.hpp"
#include "planners/fbi_planner.hpp"
#include "problem/problem.hpp"
#include "problem/problem_normalizer.hpp"
#include "util/logger.hpp"
#include "util/memory_tracker.hpp"
#include "util/stats.hpp"

#include "z3++.h"

namespace {

int write_result(const PlanGenerationResult& result, const std::string& output_file) {
    std::fstream output(output_file, std::ios::out | std::ios::trunc | std::ios::binary);
    if (!output || !result.SerializeToOstream(&output)) {
        bp::Logger::instance().error("Could not write result to file: " + output_file);
        return 1;
    }
    return 0;
}

int write_error_and_exit(const std::string& message, PlanGenerationResult_Status status,
                         const std::string& output_file) {
    bp::Logger::instance().error(message);
    PlanGenerationResult result;
    result.set_status(status);
    auto* log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_ERROR);
    log_message->set_message(message);
    int rc = write_result(result, output_file);
    google::protobuf::ShutdownProtobufLibrary();
    return rc == 0 ? 1 : rc;
}

std::vector<bp::BoundedSeqEncoder::WeightedGoal>
load_oversubscription_goals(const pb::Problem& pb_problem, const bp::Problem& problem) {
    std::vector<bp::BoundedSeqEncoder::WeightedGoal> goals;
    for (const auto& metric : pb_problem.metrics()) {
        if (metric.kind() != Metric_MetricKind_OVERSUBSCRIPTION) continue;
        for (const auto& weighted : metric.goals()) {
            goals.push_back(bp::BoundedSeqEncoder::WeightedGoal{
                bp::Expression(weighted.goal(), &problem), bp::Real(weighted.weight())});
        }
    }
    return goals;
}

// A compact one-line behaviour summary: "go=011 cb=7".
std::string behaviour_summary(const bp::DiversePlan& plan) {
    std::string summary;
    for (const auto& [dimension, value] : plan.attributes) {
        if (!summary.empty()) summary += " ";
        summary += dimension + "=" + (value.empty() ? "-" : value);
    }
    return summary;
}

void fill_plan_result(PlanGenerationResult& result, const bp::DiversePlan& plan) {
    result.set_status(PlanGenerationResult_Status_SOLVED_SATISFICING);
    *result.mutable_plan() = plan.plan.to_protobuf();

    auto& metrics = *result.mutable_metrics();
    metrics["plan_length"] = std::to_string(plan.plan.length());
    metrics["horizon"] = std::to_string(plan.horizon);
    metrics["is_new_behaviour"] = plan.is_new_behaviour ? "true" : "false";
    metrics["behaviour"] = behaviour_summary(plan);
    metrics["behaviour_expr"] = plan.behaviour_expr_str;
    for (const auto& [dimension, value] : plan.attributes) {
        metrics["behaviour." + dimension] = value;
    }
}

} // namespace

int main(int argc, char* argv[]) {
    GOOGLE_PROTOBUF_VERIFY_VERSION;

    try {
        bp::Config::instance().initialize(argc, argv);
    } catch (const std::exception& e) {
        bp::Logger::instance().error("Configuration error: " + std::string(e.what()));
        return 1;
    }
    auto& config = bp::Config::instance();
    bp::Logger::instance().set_config(&config);

    if (argc < 3) {
        bp::Logger::instance().error("Usage: " + std::string(argv[0]) +
                                     " <input_problem.pb> <output_result.pb> [OPTIONS]");
        bp::Logger::instance().error("Use --help for detailed options");
        return 1;
    }
    const std::string output_file = argv[2];

    // --- Read the problem.
    pb::Problem problem_msg;
    std::fstream input(argv[1], std::ios::in | std::ios::binary);
    if (!input || !problem_msg.ParseFromIstream(&input)) {
        bp::Logger::instance().error("Could not open or parse problem file: " +
                                     std::string(argv[1]));
        return 1;
    }

    bp::Problem problem(problem_msg);
    bp::Logger::instance().info("Loaded problem '" + problem.problem_name() + "': " +
                                std::to_string(problem.action_count()) + " actions, " +
                                std::to_string(problem.grounded_fluent_count()) +
                                " grounded fluents");

    // --- Normalize delete-then-set effects (PDDL add-after-delete semantics).
    size_t removed_effects = bp::normalize_delete_then_set(problem);
    if (removed_effects > 0) {
        bp::Logger::instance().info("[Normalize] Removed " + std::to_string(removed_effects) +
                                    " delete-then-set effects");
    }

    // --- Oversubscription metric, if any.
    auto oversubscription_goals = load_oversubscription_goals(problem_msg, problem);
    const bool is_oversubscription = !oversubscription_goals.empty();
    if (is_oversubscription) {
        bp::Logger::instance().info("Oversubscription task with " +
                                    std::to_string(oversubscription_goals.size()) +
                                    " weighted goals");
    }
    for (const auto& spec : config.planner.dimensions) {
        if (spec.name == "uv" && !is_oversubscription) {
            return write_error_and_exit(
                "The 'uv' dimension requires an oversubscription task whose metric assigns a utility per goal.",
                PlanGenerationResult_Status_UNSUPPORTED_PROBLEM, output_file);
        }
    }

    // --- Goal reachability check, action pruning, and seed lower bound.
    const size_t total_actions = problem.action_count();
    if (config.global.enable_action_removal) {
        bp::RelaxedPlanningGraph rpg(problem);
        bool goals_reachable = rpg.build();

        if (!goals_reachable && !is_oversubscription) {
            PlanGenerationResult result;
            result.set_status(PlanGenerationResult_Status_UNSOLVABLE_PROVEN);
            auto* log_message = result.add_log_messages();
            log_message->set_level(LogMessage_LogLevel_INFO);
            log_message->set_message(
                "Problem proven unsolvable: goals not reachable in the relaxed planning graph");
            int rc = write_result(result, output_file);
            google::protobuf::ShutdownProtobufLibrary();
            return rc;
        }

        config.planner.start_timestep = std::max(0, rpg.get_minimum_steps_lower_bound());
        size_t removed_actions = rpg.remove_unreachable_actions();
        std::ostringstream message;
        message << "[Action Removal] Removed " << removed_actions << "/" << total_actions
                << " unreachable actions; seed search starts at timestep "
                << config.planner.start_timestep;
        bp::Logger::instance().info(message.str());
    }

    // --- Plan.
    z3::context ctx;
    bp::FBIPlanner planner(problem, ctx, oversubscription_goals);
    bp::FBIPlanner::Result result = planner.plan();

    bp::Logger::instance().info(
        "Diverse planning finished: " + std::to_string(result.plans.size()) + " plans (" +
        std::to_string(result.new_behaviour_count) + " distinct behaviours), optimal length " +
        std::to_string(result.optimal_plan_length) + ", formula length " +
        std::to_string(result.formula_length));

    // --- Write the overall result and one result per plan.
    PlanGenerationResult overall;
    overall.set_status(result.plans.empty()
                           ? PlanGenerationResult_Status_UNSOLVABLE_INCOMPLETELY
                           : PlanGenerationResult_Status_SOLVED_SATISFICING);
    auto& metrics = *overall.mutable_metrics();
    metrics["num_plans"] = std::to_string(result.plans.size());
    metrics["new_behaviour_count"] = std::to_string(result.new_behaviour_count);
    metrics["optimal_plan_length"] = std::to_string(result.optimal_plan_length);
    metrics["formula_length"] = std::to_string(result.formula_length);
    metrics["seed_seconds"] = std::to_string(result.seed_seconds);
    metrics["diversify_seconds"] = std::to_string(result.diversify_seconds);
    metrics["memory_mb"] =
        std::to_string(bp::MemoryTracker::instance().get_current_memory_mb());
    if (!result.plans.empty()) {
        *overall.mutable_plan() = result.plans.front().plan.to_protobuf();
    }
    auto* log_message = overall.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);
    log_message->set_message("Generated " + std::to_string(result.plans.size()) +
                             " diverse plans");

    for (size_t i = 0; i < result.plans.size(); ++i) {
        PlanGenerationResult plan_result;
        fill_plan_result(plan_result, result.plans[i]);
        if (write_result(plan_result, output_file + "." + std::to_string(i)) != 0) {
            return 1;
        }
    }

    if (config.global.debug_mode) {
        bp::Stats::instance().print_all();
    }
    if (!config.global.stats_file.empty()) {
        bp::Stats::instance().write_to_file(config.global.stats_file);
    }

    int rc = write_result(overall, output_file);
    google::protobuf::ShutdownProtobufLibrary();
    return rc;
}
